openapi: 3.1.0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /users/set_password:
    post:
      tags:
      - Пользователи
      summary: Обновление пароля
      operationId: setPassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewPasswordRequest"
        required: true
      responses:
        "200":
          description: OK
  /register:
    post:
      tags:
      - auth-controller
      summary: Регистрация пользователя
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Register"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /login:
    post:
      tags:
      - auth-controller
      summary: Авторизация пользователя
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /ads:
    get:
      tags:
      - ads-controller
      summary: Получение всех объявлений
      operationId: getAllAds
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AdsDto"
    post:
      tags:
      - ads-controller
      summary: Создание нового объявления
      operationId: createAd
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                properties:
                  $ref: "#/components/schemas/AdRequestDto"
                image:
                  type: string
                  format: binary
              required:
              - properties
      responses:
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AdDto"
  /ads/{id}/comments:
    get:
      tags:
      - Комментарии
      summary: Получить комментарии объявления
      operationId: getComments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CommentsDto"
    post:
      tags:
      - Комментарии
      summary: Добавить комментарий к объявлению
      operationId: addComment
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentCreateOrUpdateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CommentDto"
  /users/me:
    get:
      tags:
      - Пользователи
      summary: Получить данные пользователя
      operationId: getUser
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDto"
    patch:
      tags:
      - Пользователи
      summary: Обновление данных пользователя
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UpdateUserDto"
  /users/me/image:
    patch:
      tags:
      - Пользователи
      summary: Обновление аватара пользователя
      operationId: updateUserImage
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
              required:
              - image
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /ads/{id}:
    get:
      tags:
      - ads-controller
      summary: Получения объявления по id
      operationId: getAd
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AdResponseDto"
    delete:
      tags:
      - ads-controller
      summary: Удаление объявления с id
      operationId: deleteAd
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: No Content
    patch:
      tags:
      - ads-controller
      summary: Обновление данных объявления с id
      operationId: updateAd
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AdDto"
  /ads/{id}/image:
    patch:
      tags:
      - ads-controller
      summary: Обновление картинки объявления
      operationId: updateAdImage
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: image
        in: query
        required: true
        schema:
          type: string
          format: binary
      responses:
        "200":
          description: OK
  /ads/{adId}/comments/{commentId}:
    delete:
      tags:
      - Комментарии
      summary: Удалить комментарий из объявления
      operationId: deleteComment
      parameters:
      - name: adId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: commentId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
    patch:
      tags:
      - Комментарии
      summary: Обновить текст комментария
      operationId: updateComment
      parameters:
      - name: adId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: commentId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentCreateOrUpdateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CommentDto"
  /images/{id}:
    get:
      tags:
      - image-controller
      operationId: getImage
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            image/png:
              schema:
                type: string
                format: byte
            image/jpeg:
              schema:
                type: string
                format: byte
            image/gif:
              schema:
                type: string
                format: byte
            image/*:
              schema:
                type: string
                format: byte
  /ads/me:
    get:
      tags:
      - ads-controller
      summary: Получение объявлений текущего пользователя
      operationId: getCurrentUserAds
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AdsDto"
components:
  schemas:
    NewPasswordRequest:
      type: object
      description: Обновление пароля пользователя
      properties:
        currentPassword:
          type: string
          description: Текущий пароль
          maxLength: 16
          minLength: 8
        newPassword:
          type: string
          description: Новый пароль
          maxLength: 16
          minLength: 8
      required:
      - currentPassword
      - newPassword
    Register:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        role:
          type: string
          enum:
          - USER
          - ADMIN
    Login:
      type: object
      properties:
        password:
          type: string
        username:
          type: string
    AdRequestDto:
      type: object
      description: Изменение объявления
      properties:
        title:
          type: string
          description: заголовок
        price:
          type: number
          description: цена товара
        description:
          type: string
          description: описание товара
    AdDto:
      type: object
      description: Объявление
      properties:
        author:
          type: integer
          format: int64
          description: id автора
        image:
          type: string
          description: картинка товара
        pk:
          type: integer
          format: int64
          description: id объявления
        price:
          type: number
          description: цена товара
        title:
          type: string
          description: заголовок объявления
    CommentCreateOrUpdateRequest:
      type: object
      description: Запрос на создание или обновление комментария
      properties:
        text:
          type: string
          description: Текст комментария
          maxLength: 64
          minLength: 8
    CommentDto:
      type: object
      description: Комментарий к объявлению
      properties:
        authorImage:
          type: string
          description: Ссылка на изображение автора
        authorFirstName:
          type: string
          description: Имя автора
        createdAt:
          type: string
          format: date-time
          description: Дата создания
        text:
          type: string
          description: Текст комментария
        author:
          type: integer
          format: int64
          description: Идентификатор автора
        pk:
          type: integer
          format: int64
          description: Идентификатор комментария
    UpdateUserDto:
      type: object
      description: Обновление пользователя
      properties:
        firstName:
          type: string
          description: Имя пользователя
          maxLength: 10
          minLength: 3
        lastName:
          type: string
          description: Фамилия пользователя
          maxLength: 10
          minLength: 3
        phone:
          type: string
          description: Телефонный номер пользователя
          pattern: "\\+7\\s?\\(?\\d{3}\\)?\\s?\\d{3}-?\\d{2}-?\\d{2}"
    UserDto:
      type: object
      description: Пользователь
      properties:
        id:
          type: integer
          format: int64
          description: Id пользователя
        email:
          type: string
          description: E-mail пользователя
        firstName:
          type: string
          description: Имя пользователя
        lastName:
          type: string
          description: Фамилия пользователя
        phone:
          type: string
          description: Телефонный номер пользователя
        role:
          type: string
          description: Роль пользователя
          enum:
          - USER
          - ADMIN
        image:
          type: string
          description: Аватар пользователя
    AdsDto:
      type: object
      description: Список объявлений
      properties:
        count:
          type: integer
          format: int32
          description: Количество объявлений
        results:
          type: array
          description: Список объявлений
          items:
            $ref: "#/components/schemas/AdDto"
    AdResponseDto:
      type: object
      description: Объявление
      properties:
        pk:
          type: integer
          format: int64
          description: Индификатор объявления
        authorFirstName:
          type: string
          description: Имя автора
        authorLastName:
          type: string
          description: Фамилия автора
        description:
          type: string
          description: Описание товара
        email:
          type: string
          description: Email автора
        image:
          type: string
          description: путь к картинке товара
        phone:
          type: string
          description: Номер телефона автора
        price:
          type: number
          description: Цена товара
        title:
          type: string
          description: Название товара
    CommentsDto:
      type: object
      description: Количество комментариев
      properties:
        count:
          type: integer
          format: int32
          description: Количество комментариев
        results:
          type: array
          description: Комментарии
          items:
            $ref: "#/components/schemas/CommentDto"
